
#General Settings
[settings]
	#Enable version checker
	showUpdates = true

#Effect Settings
[general]
	#Determine random virus msx gene count
	randomVirusGeneCount = 8
	#Enables random virus creation with random genes applied
	randomVirusCreation = true
	#Every N mobs there will be chance to spawn random wild virus
	randomVirusMobCount = 20
	#Determine random virus spawn chance from 1 to 100
	randomVirusSpawnChance = 5

#General Settings
[item]
	#Default effect spread radius for vial
	vialSpreadRadius = 10.0

#Machine settings
[timers]
	#Default machine total work time
	defaultVaccineCreatorProcessTime = 1200
	#Default machine total work time
	defaultDNAModifierProcessTime = 1200
	#Default machine total work time
	defaultVirusReplicatorProcessTime = 12000
	#Default machine total work time
	defaultCureStationProcessTime = 1200

#General Settings
[death]
	#Save Bionisation effects and stats after player death
	saveAfterDeath = true

#Effect Settings
[cures]
	#Default antibiotic effect duration
	defaultAntibioticDuration = 3200
	#Default vaccine_creator cure chance
	defaultVaccineCureChance = 50
	#Default vaccine_creator effect duration
	defaultVaccineDuration = 3200
	#Default virus immunity effect duration
	defaultImmunityDuration = 360000

#Time Settings
[timings]
	#Default mutation period for every B4 effect (ticks)
	defaultMutationPeriod = 24000
	#Default custom virus random duration (without Infinity Gene)
	defaultCustomVirusDuration = 2720000
	#Default Bionisation effect sync period (only for specific effects) (ticks)
	defaultEffectSyncPeriod = 35

#Override settings
[overrides]
	#Modify effect durations (will be applied to all new instances). Format: name:duration. Example: Rabies:60000. Leave -1 for infinity
	effectDurations = []
	#Effect names that should be disabled (they wont tick)
	disabledEffects = []
	#Modify effect trigger chances. Format: id:chance. Example: 2:90 (2 i.e. Bleeding Effect, 90 - chance (0-100))
	effectChances = []
	#Gene names that should be disabled (they wont tick)
	disabledGenes = []

